[tools]
claude = "latest" # [skip ci]
go = "1.27"
pinact = "latest" # [skip ci]

[tasks.pre-commit]
depends = ["ci"]

[tasks.ci]
depends = ["vet", "test", "fmt"]

[tasks.vet]
run = "go vet"

[tasks.test]
run = "go test"

[tasks.build]
run = "go build"

[tasks.fmt]
run = "go fmt"
